version: 2
reference:

  ## Workspaces
  workspace: &workspace
    ~/code

  ## Docker image configurations
  android_config: &android_config
    working_directory: *workspace
    docker:
      - image: circleci/android:api-28-node8-alpha
    environment:
      TERM: dumb
      _JAVA_OPTIONS: "-Xmx2048m -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"
      GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx2048m"'

  ## Cache
  gradle_key: &gradle_key
    jars-v1-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}

  restore_gradle_cache: &restore_gradle_cache
    restore_cache:
      key: *gradle_key

  save_gradle_cache: &save_gradle_cache
    save_cache:
      key: *gradle_key
      paths:
        - ~/.gradle
        - ~/.m2

  ## Dependencies

  android_dependencies: &android_dependencies
    run:
      name: Download Android Dependencies
      command: ./gradlew androidDependencies

jobs:
  # unit test
  build:
    <<: *android_config
    steps:
      - android list targets
      - echo no | android create avd -n emulatorwithgoogleapi22 -t 12 --tag google_apis
      - echo 'vm.heapSize=512' >> ~/.android/avd/emulatorwithgoogleapi22.ini
      - echo 'hw.ramSize=1024' >> ~/.android/avd/emulatorwithgoogleapi22.ini
      - cat ~/.android/avd/emulatorwithgoogleapi22.ini
      - emulator -avd emulatorwithgoogleapi24 -no-audio -no-window :
          background: true
          parallel: true
      - circle-android wait-for-boot
      - adb shell input keyevent 82
      - adb shell svc power stayon true
      - adb shell settings put global window_animation_scale 0
      - adb shell settings put global transition_animation_scale 0
      - adb shell settings put global animator_duration_scale 0
      - checkout
      - *restore_gradle_cache
      - *android_dependencies
      - *save_gradle_cache
      - run:
          name: Run test
          command: ./gradlew assembleDebug connectedAndroidTest
